# Configuration for the Amethyst development site
#
# DO NOT COPY
#
# To create your own site with this theme, use the example branch as
# your clean and minimal starting point:
# https://github.com/qunitjs/jekyll-theme-amethyst/tree/example
#
# -------

# Site settings
#
# Docs: https://jekyllrb.com/docs/configuration/
title: Amethyst Demo
description: "An amazing website."
url: https://qunitjs.github.io
baseurl: /jekyll-theme-amethyst
# For pages (not blog posts) this is equivalant to /:title/
permalink: /:year/:month/:day/:title/
lang: en
timezone: UTC
# Files that will not be converted or published
exclude:
  # Exclude internal repo files from site output
  - docs
  - lib
  # Avoid the following on GitHub CI:
  # > Error: could not read file
  # > vendor/jekyll/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb:
  # > Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>':
  # > Document does not have a valid date in the YAML front matter.
  - vendor
plugins:
  - jekyll-theme-amethyst


# Theme settings
#
# Amethyst theme options are documented at:
# https://github.com/qunitjs/jekyll-theme-amethyst/blob/main/docs/config.md
#
theme: jekyll-theme-amethyst
amethyst:
  edituri_base: https://github.com/qunitjs/jekyll-theme-amethyst/blob/main/
  release_base: https://github.com/qunitjs/qunit/releases/tag/
  github: qunitjs
  chat: https://app.element.io/#/room/#qunitjs_qunit:gitter.im
  # https://github.com/qunitjs/jekyll-theme-amethyst/blob/main/docs/getting-started.md#enable-typesense
  typesense:
    origin: https://typesense.jquery.com
    collection: amethyst_demo
    search_only_api_key: Zh8mMgohXECel9wjPwqT7lekLSG3OCgz


# Conversion settings
#
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: "1,2"


# Sass settings
#
# Docs: https://jekyllrb.com/docs/assets/#sassscss
sass:
  style: compressed
  sourcemap: never


# Blog archives
#
# Docs: https://github.com/jekyll/jekyll-archives/
jekyll-archives:
  enabled:
    - year
  layout: posts-year
  permalinks:
    year: "/:year/"
