# Site settings
#
# Docs: https://jekyllrb.com/docs/configuration/
title: Amethyst Demo
description: An amazing website.
# For pages (not blog posts) this is equivalant to /:title/
permalink: /:year/:month/:day/:title/
lang: en
timezone: UTC
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: "1,2"
sass:
  # https://jekyllrb.com/docs/assets/#sassscss
  style: compressed
  sourcemap: never
exclude:
  # Don't include these files in the website
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md


# Theme settings
#
# Amethyst theme options are documented at:
# https://github.com/qunitjs/jekyll-theme-amethyst/blob/main/docs/config.md
#
theme: jekyll-theme-amethyst
amethyst:
  favicon:
  home_href:
  header_logo:
  # Base URI for "Edit this page" link in the footer.
  # When set, this is combined with the relative path to the Markdown file in the repo.
  #
  # Example: https://github.com/qunitjs/qunitjs.com/blob/main/
  edituri_base: https://github.com/qunitjs/jekyll-theme-amethyst/blob/example/
  release_base:
  mastodon:
  twitter:
  github: qunitjs
  gitter:
  typesense:
    origin:
    collection:
    search_only_api_key:


# Blog archives
#
# Docs: https://github.com/jekyll/jekyll-archives/
jekyll-archives:
  enabled:
    - year
  layout: posts-year
  permalinks:
    year: "/:year/"
