# Configuration for the Amethyst development site
#
# DO NOT COPY
#
# To create your own site with this theme, use the example branch as
# your clean and minimal starting point:
# https://github.com/qunitjs/jekyll-theme-amethyst/tree/example
#
# -------

# Site settings
#
# Docs: https://jekyllrb.com/docs/configuration/
title: Amethyst Demo
description: "An amazing website."
url: https://qunitjs.github.io
baseurl: /jekyll-theme-amethyst
# For pages (not blog posts) this is equivalant to /:title/
permalink: /:year/:month/:day/:title/
lang: en
timezone: UTC
# Files that will not be converted or published
exclude:
  # Exclude internal repo files from site output
  - docs
  - lib
  # Avoid the following on GitHub CI:
  # > Error: could not read file
  # > vendor/jekyll/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb:
  # > Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>':
  # > Document does not have a valid date in the YAML front matter.
  - vendor
plugins:
  - jekyll-theme-amethyst


# Theme settings
#
# Amethyst theme options are documented at:
# https://github.com/qunitjs/jekyll-theme-amethyst/blob/main/docs/config.md
#
theme: jekyll-theme-amethyst
amethyst:
  edituri_base: https://github.com/qunitjs/jekyll-theme-amethyst/blob/main/
  release_base: https://github.com/qunitjs/qunit/releases/tag/
  github: qunitjs
  chat: https://app.gitter.im/#/room/#qunitjs_qunit:gitter.im
  # https://github.com/qunitjs/jekyll-theme-amethyst/blob/main/docs/getting-started.md#enable-typesense
  typesense:
    origin: https://typesense.jquery.com
    collection: amethyst_demo
    search_only_api_key: Zh8mMgohXECel9wjPwqT7lekLSG3OCgz


# Conversion settings
#
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: "1,2"


# Sass settings
#
# Docs: https://jekyllrb.com/docs/assets/#sassscss
sass:
  style: compressed
  sourcemap: never
  # Sass has deprecated `@import` but I failed to find a way to make
  # the new Sass module system do what we need via `@use`.
  #
  # Previous attempt at [1] was rolled back because while it was
  # workable for the demo, it fell apart when using it in a production
  # site like qunitjs.com because `@use` seems to favor nearby files
  # even after you have left the site.
  # Example: `assets/styles.scss`, defined in theme.
  # - `assets/styles.scss` @use `amethyst`, defined in theme.
  # - `amethyst.scss` @use `amethyst-variables-all`, defined in theme.
  # - `amethyst-variables-all` @use `amethyst-variables` which is
  #    overridden by the current site, but while @import prefers
  #    the site directory, @use seems to favour the nearest, thus
  #    making extension points impossible.
  #
  # Silence the deprecation for now, and let's hope this matures
  # and gets better documented some time before Oct 2026 [2].
  #
  # [1]: https://github.com/qunitjs/jekyll-theme-amethyst/commit/356962ef961c8d06741147fb4e4b2e56d917a080
  # [2] https://sass-lang.com/blog/import-is-deprecated/
  # [3] https://sass-lang.com/blog/the-module-system-is-launched/
  # [4] https://github.com/jekyll/minima/issues/815
  quiet_deps: true


# Blog archives
#
# Docs: https://github.com/jekyll/jekyll-archives/
jekyll-archives:
  enabled:
    - year
  layout: posts-year
  permalinks:
    year: "/:year/"
