name: spider-check
on:
  # Once a week on Friday at 00:00
  schedule:
    - cron: '0 0 * * 5'
  # Or manually
  workflow_dispatch:
  # Or when developing this workflow
  push:
    paths:
      - .github/workflows/spider-check.yaml
  pull_request:
    paths:
      - .github/workflows/spider-check.yaml

jobs:
  spider-check:
    env:
      # Site address to crawl
      #
      # MY_SITE: https://example.org
      # MY_SITE: https://example.github.io
      # MY_SITE: https://example.github.io/my-project/
      #
      MY_SITE: https://qunitjs.github.io/jekyll-theme-amethyst/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jquery/hydra-link-checker
          ref: v2.0.0

      - name: Run hydra-link-checker
        run: python3 hydra.py "$MY_SITE"
