name: spider-check
on:
  # Once a week on Thursday at 02:15
  schedule:
    - cron: '15 2 * * 4'
  # Or manually
  workflow_dispatch:
  # Or when developing this workflow
  push:
    paths:
      - .github/workflows/spider-check.yaml
  pull_request:
    paths:
      - .github/workflows/spider-check.yaml

jobs:
  spider-check:
    # Includes Python 3
    # https://github.com/actions/virtual-environments/blob/ubuntu20/20210318.0/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jquery/hydra-link-checker
          ref: v1.0.2

      - name: Run hydra-link-checker
        run: python3 hydra.py "https://qunitjs.github.io/jekyll-theme-amethyst/"
